import type { SubtitleStyle } from "./types";

export const DEFAULT_SUBTITLE_STYLE: SubtitleStyle = {
  fontFamily: "Inter",
  fontSize: 48,
  fontWeight: 700,
  letterSpacing: 0,
  lineHeight: 1.2,
  color: "#FFFFFF",
  textOpacity: 100,
  bgColor: "#000000",
  bgOpacity: 0,
  bgPadding: 8,
  bgRadius: 4,
  strokeEnabled: false,
  strokeColor: "#000000",
  strokeWidth: 0,
  shadowEnabled: true,
  shadowColor: "#000000",
  shadowBlur: 6,
  shadowX: 0,
  shadowY: 2,
  hAlign: "center",
  vAlign: "bottom",
  customX: null,
  customY: null,
  margin: 40,
  animIn: "fade",
  animOut: "fade",
  animDuration: 250,
};

export interface SubtitlePreset {
  id: string;
  name: string;
  style: SubtitleStyle;
}

export const SUBTITLE_PRESETS: SubtitlePreset[] = [
  {
    id: "youtube",
    name: "YouTube Style",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Roboto",
      fontWeight: 700,
      color: "#FFFFFF",
      bgOpacity: 0,
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowEnabled: true,
      shadowBlur: 4,
      shadowY: 2,
      hAlign: "center",
      vAlign: "bottom",
      fontSize: 44,
    },
  },
  {
    id: "netflix",
    name: "Netflix Style",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Inter",
      fontWeight: 500,
      color: "#FFFFFF",
      bgColor: "#000000",
      bgOpacity: 60,
      bgPadding: 12,
      bgRadius: 6,
      strokeEnabled: false,
      shadowEnabled: false,
      hAlign: "center",
      vAlign: "bottom",
      fontSize: 40,
    },
  },
  {
    id: "tiktok",
    name: "TikTok Style",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 800,
      color: "#FFFFFF",
      bgColor: "#8B5CF6",
      bgOpacity: 90,
      bgPadding: 14,
      bgRadius: 10,
      strokeEnabled: false,
      shadowEnabled: true,
      shadowBlur: 10,
      shadowColor: "#000000",
      hAlign: "center",
      vAlign: "middle",
      fontSize: 56,
      animIn: "scale",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Inter",
      fontWeight: 400,
      color: "#FFFFFF",
      bgOpacity: 0,
      strokeEnabled: false,
      shadowEnabled: true,
      shadowBlur: 3,
      hAlign: "left",
      vAlign: "bottom",
      fontSize: 32,
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Poppins",
      fontWeight: 700,
      color: "#FDE047",
      bgOpacity: 0,
      strokeEnabled: true,
      strokeColor: "#111827",
      strokeWidth: 2,
      shadowEnabled: false,
      hAlign: "center",
      vAlign: "middle",
      fontSize: 52,
      animIn: "wordByWord",
    },
  },
  {
    id: "news",
    name: "News Ticker",
    style: {
      ...DEFAULT_SUBTITLE_STYLE,
      fontFamily: "Roboto",
      fontWeight: 600,
      color: "#FDE047",
      bgColor: "#000000",
      bgOpacity: 85,
      bgPadding: 10,
      bgRadius: 2,
      strokeEnabled: false,
      shadowEnabled: false,
      hAlign: "center",
      vAlign: "bottom",
      fontSize: 38,
    },
  },
];

export const FONT_OPTIONS: { value: string; label: string }[] = [
  { value: "Inter", label: "Inter" },
  { value: "Roboto", label: "Roboto" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Poppins", label: "Poppins" },
  { value: "Lato", label: "Lato" },
  { value: "Oswald", label: "Oswald" },
  { value: "Raleway", label: "Raleway" },
  { value: "Nunito", label: "Nunito" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Bebas Neue", label: "Bebas Neue" },
  { value: "Bangers", label: "Bangers" },
  { value: "Permanent Marker", label: "Permanent Marker" },
  { value: "Pacifico", label: "Pacifico" },
  { value: "Dancing Script", label: "Dancing Script" },
  { value: "Lobster", label: "Lobster" },
  { value: "Anton", label: "Anton" },
  { value: "Righteous", label: "Righteous" },
  { value: "Titan One", label: "Titan One" },
];

export const GOOGLE_FONTS_LINK = `https://fonts.googleapis.com/css2?${FONT_OPTIONS.map(
  (f) => `family=${f.value.replace(/ /g, "+")}:wght@100;300;400;500;600;700;800;900`,
).join("&")}&display=swap`;

export const COLOR_SWATCHES = [
  "#FFFFFF",
  "#000000",
  "#FDE047",
  "#22D3EE",
  "#EF4444",
  "#10B981",
  "#3B82F6",
  "#F97316",
  "#EC4899",
  "#8B5CF6",
];
